import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Challenge 01: Import SiteHeader and SiteFooter here, then add them to the body below.
// import SiteHeader from "@/app/components/SiteHeader";
// import SiteFooter from "@/app/components/SiteFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Challenge 01: Update this metadata to reflect the Music Explorer site.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout wraps every page in the app with the shared header and footer.
// The {children} prop is replaced by whatever page the user is visiting.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        {/* Challenge 01: Add <SiteHeader /> here */}
        {children}
        {/* Challenge 01: Add <SiteFooter /> here */}
      </body>
    </html>
  );
}
